export { buildFinancials, cultivationFinancials, weeksToDate, ALL_FACILITIES_LABEL, type FinancialsInput } from './build'
export { costsAndMargin, effectsOf, forecastMoney, periodFrom, revenueRange, sumLines, wasteKgPerM2, weekLines } from './calc'
export { EXAMPLE_PRICES, EXAMPLE_RATES, PLACEHOLDER_LED_W_PER_M2, FINANCIAL_KPI } from './defaults'
export { examplePricesInUse, priceOf, ratesOf } from './prices'
export { compactMoney, moneyText, rateInputsOf, ratesRowFor, signedMoney, validateRates, validateRateText, variancePercent, type RatesInput } from './text'
export type * from './types'
